### ISSUE TITLE
Nest type

### ISSUE THREAD

**Issue by stwiss** [manandearth/hirundia#23]
Need nest construction types adding:

Roof
Beam
Patio 
Light Fitting

* An option to manually add since nest construction types vary **

**Comment by manandearth** [comment]
@stwiss,

 The reason for having a set for the nest types is so that they could be grouped later for analysis. 
I think that having a text field in place of a set can also lead to inconsistency (spelling mistakes/ capitals/ language). Imagine a user typing in `beam` and a different user typing in `wooden-beam`.

Think also what are the possible uses for the nest type data. Perhaps some should be grouped (ceiling/ light-fitting/roof-beam)? 
 

If you find there are types missing could you please suggest a complete set?
:thinking:

**Comment by stwiss** [comment]
Yes I see the problem with leaving it open. 

So a complete set:
balcony
window
cornice
patio
crack
ceiling
gable
